[package]
name = "netsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.0" }
once_cell = "1.19.0"
rand = "0.8.5"
regex = "1.5.4"
uuid = "1.8.0"
